### ISSUE TITLE
Java Module support

### ISSUE THREAD

**Issue by MaSven** [cretz/pgnio#1]
Since this projects has no dependencies would it be possible to get support for the Java module system? I could do a pull request if wanted.

**Comment by MaSven** [comment]
They are deployed as normal jar to maven. The only difference is that there is a Info-module.class file in the root folder.

**Comment by MaSven** [comment]
But in the moment there is not really a way to support effectively module path and classpath from Gradle and maven. I will wait with the PR till java11 ist out. Just remind me then if you think it is appropriate.

**Comment by cretz** [comment]
Sure. I'll close this for now, but leave open the comments.
